### ISSUE TITLE
architecture: x86 + bits: 64

### ISSUE THREAD

**Issue by RobertEcker** [hexydec/agentzero#7]
Hi - tnx for the good UA parser ;)

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko)`

Architecture | x86
Bits | 64

I think that can't be correct.

btw: no need to prefix standard PHP functions with a backslash "\\", easier to read then (AFAIK except same custom function name).
maybe it is a liiiiittle bit faster with "\\" (no need of the namespace resolution process).
and you have to use - for example - "use stdClass;" (after namespace).

**Comment by hexydec** [comment]
Note sure which bit you think is not correct. The UA string says "Intel", indicating that is it an Intel processor, which will be x86. All Macitosh devices that have Mac OS X version 10.6 or higher are 64 bit operating systems.

Regarding prefixing library functions with a backslash when in a namespaced context, you are correct that this is a performance enhancement that prevents PHP from looking up the symbol in the current namespace before falling back to the root namespace.

When using it to lookup one or two UA strings this won't make much difference, when you are looking up thousands the speed improvement is welcome. I developed this library to support another project I am working on which does just this. I built it with performance in mind, which is why it does mostly string matching, and why the library functions are all backslashed.
